<?xml version="1.0" encoding="UTF-8"?>
<CustomApplication xmlns="http://soap.sforce.com/2006/04/metadata">
    <defaultLandingTab>standard-home</defaultLandingTab>
    <description>Automatically generated by EscapeNotes. Remove this text to write protect from EscapeNotes.</description>
    <label>Quotes &amp; Orders 2011</label>
    <tab>QuoteOrder__c</tab>
    <tab>ExchRate__c</tab>
</CustomApplication>
